@HostAddress = http://localhost:5021

### Get all todos
GET {{HostAddress}}/todos
Accept: application/json

### Create new todo
POST {{HostAddress}}/todos
Content-Type: application/json

{
  "title": "Learn .NET",
  "isComplete": false
}

### Delete a todo
DELETE {{HostAddress}}/todos/1


###
