<Project Sdk="Microsoft.NET.Sdk">

    <Sdk Name="Aspire.AppHost.Sdk" Version="9.1.0"/>

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsAspireHost>true</IsAspireHost>
        <UserSecretsId>3af791a6-de41-45d7-9d6f-57ed525b30e4</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Aspire.Hosting.AppHost" Version="9.1.0"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Backoffice.API\Backoffice.API.csproj" />
        <ProjectReference Include="..\ToDo.Api\ToDo.Api.csproj" />
    </ItemGroup>

</Project>
